# netlify.toml
[[redirects]]
  from = "/*"
  to = "https://script.google.com/macros/s/AKfycbwKiJRjHPWTeB7YeQWTecxMvY2PNkRgEL0szOZXIBJTb41-lc2yMckmm0ceq1BCkUcPtg/exec"
  status = 200
  force = true